algorithm: 
  name: "auto_encoder"

optimizer:
  opt: "Adam"
  lr: 1.0e-3
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  weight_decay: 1.0e-5
  grad_clip: 5.0
  
scheduler:
  sched: ReduceLROnPlateau
  factor: 0.5
  patience: 5  

net:
  z_dim: 128
  initialize_weights: True

data:
  cache: 
  augment: False
  fraction: 1.0
  nbs: -1
  batch_size: 1024
  num_workers: 4
  shuffle: False
  

  
  