algorithm: 
  name: "hyper_mamba"
  img_size: 640
  use_dfl: True
  reg_max: 16
  topk: 10
  alpha: 0.5
  beta: 6.0
  close_mosaic: 10

  # loss weight
  box: 7.5 # (float) box loss gain
  cls: 0.5 # (float) cls loss gain (scale with pixels)
  dfl: 1.5 # (float) dfl loss gain

  # detection
  iou_thres: 0.7
  conf_thres_val: 0.001
  conf_thres_det: 0.25

  nbs: 64 # (int) nominal batch size, -1 represent no 

optimizer:
  type: "Adam"
  learning_rate: 1.0e-3
  final_factor: 0.01
  beta1: 0.937
  beta2: 0.999
  eps: 1.0e-8
  weight_decay: 0.0005

  # type: "SGD"
  # learning_rate: 0.01
  # final_factor: 0.01
  # momentum: 0.937
  # weight_decay: 0.0005

  grad_clip: 1.0
  warmup_epochs: 3.0
  warmup_epochs: 3.0 # (float) warmup epochs (fractions ok)
  warmup_momentum: 0.8 # (float) warmup initial momentum
  warmup_bias_lr: 0.0 # 0.1 # (float) warmup initial bias lr
  
scheduler:
  # type: "ReduceLROnPlateau"
  # factor: 0.5
  # patience: 5 
  
  type: CustomLRDecay


net:
  initialize_weights: True
  