algorithm: 
  name: "yolo_mm"
  default_img_size: 640

  # detection
  iou_threshold: 0.5
  conf_threshold: 0.1
  nms_threshold: 0.5

optimizer:
  type: "Adam"
  learning_rate: 1.0e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  weight_decay: 0.0005
  grad_clip: 1.0
  
scheduler:
  # type: "ReduceLROnPlateau"
  # factor: 0.5
  # patience: 5 
  
  type: LRWarnupDecay
  epochs: [100, 200]
  scales: [0.1, 0.01]

model:
  initialize_weights: True

data_loader:
  num_workers: 6
  shuffle: True
  batch_size: 256
  subdevision: 1
  