algorithm: "auto_encoder"

optimizer:
  type: "Adam"
  learning_rate: 1.0e-3
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  weight_decay: 1.0e-5
  
scheduler:
  type: ReduceLROnPlateau
  factor: 0.5
  patience: 5  

model:
  initialize_weights: True

training:
  d_grad_clip: 5.0
  g_grad_clip: 5.0