algorithm: "gan"

optimizer:
  type: "Adam"
  # 生成器参数
  g_learning_rate: 1.0e-4
  g_beta1: 0.9
  g_beta2: 0.999
  g_eps: 1.0e-8
  g_weight_decay: 0
  # 判别器参数
  d_learning_rate: 1.0e-4
  d_beta1: 0.9
  d_beta2: 0.999
  d_eps: 1.0e-8
  d_weight_decay: 0
  
scheduler:
  type: ReduceLROnPlateau
  factor: 0.5
  patience: 5

model:
  initialize_weights: True
  
training:
  grad_clip: 5.0
  n_discriminator: 5