algorithm: 
  name: "auto_encoder"

optimizer:
  type: "Adam"
  learning_rate: 1.0e-3
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  weight_decay: 1.0e-5
  grad_clip: 5.0
  
scheduler:
  type: ReduceLROnPlateau
  factor: 0.5
  patience: 5  

model:
  initialize_weights: True

data_loader:
  num_workers: 4
  shuffle: True
  batch_size: 256
  subdevision: 1