algorithm: 
  name: "yolo_v3"
  default_img_size: 416
  anchor_nums: 3
  anchors: 
    - [10, 13]
    - [16, 30]
    - [33, 23]
    - [30, 61]
    - [62, 45]
    - [59, 119]
    - [116, 90]
    - [156, 198]
    - [373, 326]
  anchor_scale_threshold: 4
  # loss
  b_weight : 0.5 # bboxes loss weight
  o_weight : 1.0  # object loss weight
  c_weight : 0.5  # cls loss weight
  # detection
  iou_threshold: 0.5
  conf_threshold: 0.1
  nms_threshold: 0.5

optimizer:
  type: "Adam"
  learning_rate: 3.0e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  weight_decay: 0.0005
  grad_clip: 1.0
  
scheduler:
  # type: "ReduceLROnPlateau"
  # factor: 0.5
  # patience: 5 
  
  type: custom

model:
  initialize_weights: True

data_loader:
  num_workers: 6
  shuffle: True
  batch_size: 256
  subdevision: 1
  