algorithm: 
  name: "yolo_v3"
  default_img_size: [3, 416, 416]
  anchor_nums: 3
  anchor_sizes: 
    - [10, 13]
    - [16, 30]
    - [33, 23]
    - [30, 61]
    - [62, 45]
    - [59, 119]
    - [116, 90]
    - [156, 198]
    - [373, 326]
  anchor_scale_threshold: 4
  # loss
  b_weight : 0.05 # bboxes loss weight
  o_weight : 1.0  # object loss weight
  c_weight : 0.5  # cls loss weight
  # detection
  iou_threshold: 0.5
  obj_exist_threshold: 0.5

optimizer:
  type: "Adam"
  learning_rate: 1.0e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  weight_decay: 1.0e-5
  grad_clip: 1.0
  
scheduler:
  type: ReduceLROnPlateau
  factor: 0.5
  patience: 5  

model:
  initialize_weights: True

  