algorithm: 
  name: "yolo_v3"
  image_size: [3, 416, 416]
  num_classes: 80
  num_anchors: 3
  anchor_sizes: 
    - [10, 13]
    - [16, 30]
    - [33, 23]
    - [30, 61]
    - [62, 45]
    - [59, 119]
    - [116, 90]
    - [156, 198]
    - [373, 326]
  # loss权重
  b_weight : 0.05
  o_weight : 1.0
  c_weight : 0.5

optimizer:
  type: "Adam"
  learning_rate: 1.0e-3
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  weight_decay: 1.0e-5
  grad_clip: 5.0
  
scheduler:
  type: ReduceLROnPlateau
  factor: 0.5
  patience: 5  

model:
  initialize_weights: True

  